### ISSUE TITLE
Beta resulting result(ver.2)

### ISSUE THREAD

**Issue by nighttwo1** [18-2-SKKU-OSS/2018-2-OSS-E2#15]
해결된 부분
- player창에 들어가면 게임이 멈추는 현상이 해결됨.

문제점
- 게임이 끝나고 fail된 이후에 다시 시작하려면 게임을 완전히 껐다가 다시 켜야됨. stage 종료 이후 바로 다시 시작할 수 있게 구현했으면 좋겠음.

**Comment by nighttwo1** [comment]
player 창에 들어가면 게임이 종료되어버림. 이거 두번째로 베타 테스트 하러 갔을 때 수정되어있었는데 누가 했는지 알려주세요!

**Comment by arensis-julia** [comment]
그거 제가 최신버전으로 바꾸긴 했습니다.
저번 이슈 코멘드로 달아놨어요
