### ISSUE TITLE
Wiki comment

### ISSUE THREAD

**Issue by arensis-julia** [18-2-SKKU-OSS/2018-2-OSS-E2#16]
1. 우리 프로젝트 소개
2. 할 일 (역할)
3. 마일스톤
4. 진행상황
4-1. 각자 앞으로 해야할 일
5. 진행완료
6. 이슈거리
7. 매인 이슈 해결 방법

iCampus에 올린 자료 참고 요청 부탁

**Comment by nighttwo1** [comment]
wiki 업데이트 중 진행 상황과 이슈거리가 비슷하여  이슈거리와 메인 이슈 해결 방법을 삭제하고 진행상황에 추가하는 방향으로 작성하려고 함. 대신에 마지막에 완료한 부분, 진행중인 부분, 앞으로 진행해야하는 부분에 대해 간략하게 다시 나타내려고함.

**Comment by nighttwo1** [comment]
프로젝트 소개란이 빈약한듯하여 readme를 참고하면 그림을 통해 이해하기 쉬울 것이라고 생각해서 readme 링크를 기재함.
