### ISSUE TITLE
Role Divided

### ISSUE THREAD

**Issue by arensis-julia** [18-2-SKKU-OSS/2018-2-OSS-E2#17]
역할 수행 과정 장윤서언니한테 현황 보고 부탁드립니다.

김현주 : GitHub Page 개선, Stage의 Asset등을 개선하여 조금 더 현실감 있게 수정, 게임 내 UI/UX수정
유태우 : Stage의 Asset등을 개선하여 조금 더 현실감 있게 수정, 코드 리팩토링 및 버그 수정
류성희 : GitHub Page 개선, 게임 내부 코드의 최적화
서유영 : 일러스트 및 UI/UX 수정
장윤서 : 게임 메뉴얼 작성 및 CBT

**Comment by nighttwo1** [comment]
1. 본인이 계획한 일
2. 진행중인 일 + 완료된 일 + 일을 진행하면서 생긴 문제점
* 11/13-11/20
* 11/21-11/27
* 11/28-12/4
* 12/4-12/11
각 기한에 맞춰서 구체적으로 작성해주세요. 자세하게 작성부탁드립니다.
