### ISSUE TITLE
Wiki modify - Request

### ISSUE THREAD

**Issue by arensis-julia** [18-2-SKKU-OSS/2018-2-OSS-E2#20]
저번 수업시간에 repository 꼬였어가지고 본 프로젝트인 URGS에다가 실수로 commit 한 기록을 남겼습니다.
다시 새로 이 repository에 반영할 터이니 이거 wiki 에다가 코멘트 달아주시기 바랍니다.
(나중에 제가 했던 기록들 정리해서 한꺼번에 다시한번 올리겠습니다)

[해당 커밋](https://github.com/SKKU-VRAR/URGS/commit/26ae7107bf143a7a5ffa839369d4f4616a00d9d0)

**Comment by nighttwo1** [comment]
확인하였고 수정하였습니다. 다시 commit해주세요~
