### ISSUE TITLE
readme modify - Request

### ISSUE THREAD

**Issue by arensis-julia** [18-2-SKKU-OSS/2018-2-OSS-E2#25]
Scene 화면이 바뀌었습니다.
화면 바뀐거 참조해서 붙여놔주세요

**Comment by nighttwo1** [comment]
? 어디서 확인할 수 있나요?? 혹시 게임 다시 실행해서 확인해야되나요?

**Comment by arensis-julia** [comment]
실제 게임 화면은 게임을 다시 실행해서 확인해야하지만 unity를 이용해서 scene을 확인할 수도 있습니다
