### ISSUE TITLE
my role - sum

### ISSUE THREAD

**Issue by arensis-julia** [18-2-SKKU-OSS/2018-2-OSS-E2#33]
[지금까지 한 일]
- 깃허브 페이지 작성, 수정
- .gitignore 파일을 만들어 meta 파일 등 매번 커밋할 필요가 없는 파일을 무시하게 만들기
- 스테이지 1 내의 가구 더 높은 퀄리티로 바꾸기
- 스테이지 1 내부의 벽, 바닥의 texture 바꾸기
- 스테이지 1 내부의 오브젝트 더 만들기
- 스테이지 1 레벨 조정하기 (타이머를 600초로 높이고 과자봉지 버리는 것을 더 분산시킴)
- readme, wiki 리뷰
- 버그 조정

[앞으로 할 일]
-  스테이지 1 내부에서 오브젝트와 인터렉트할 때 사운드 조정 가능하게 하기
- 가능하다면 스테이지 2 역시 만들어 연결시키기

**Comment by mzyt3569** [comment]
[지금까지 한 일]

* 깃허브 페이지 익히기
* 광원 조정 기능 구현
* 광원 조정 스위치 역할 구현
* 광원과 광원 조정 스위치를 관리하고 쉽게 유지보수할 수 있는 광원 시스템 구현
* 광원 시스템 모듈화 및 배포

[앞으로 할 일]

* 스테이지 1 내의 광원 시스템 적용
* 음향 시스템 구현
* 가능하다면 스테이지 2 구상 및 구현

**Comment by jyeha** [comment]
[지금까지 한 일]

- 깃허브 페이지 익히기
- UI 내의 버튼 디자인 수정
- UI 폰트 변경
- UI 캔버스 레이아웃 수정
- 2분할 레이아웃에서 3분할로 수정하여 로고 항시 유지
- StageInfo에서 Back Button을 누르면 Stage가 아닌 Select화면으로 가는 현상 수정
- 전체적인 가독성 상승

[앞으로 할 일]

- 스테이지 내의 Pause 시의 UI 구현
- 스테이지 내의 UI 수정 : 남은 시간 수정, 달성도, 스킬목록 등의 UI 추가
- 캐릭터 추가하여 플레이어가 원하는 캐릭터 설정 가능하도록 수정
