### ISSUE TITLE
Wiki and readme update needed

### ISSUE THREAD

**Issue by nighttwo1** [18-2-SKKU-OSS/2018-2-OSS-E2#7]
Wiki에 추가하면 좋을 듯한 내용
* 선정된 프로젝트에 관한 간략한 소개
* 활동계획
* 개인별 역할에 관한 내용

Readme 작성에 필요한 내용
* 사용방법(메뉴얼)
* 프로젝트에 대한 간략한 소개

**Comment by nighttwo1** [comment]
wiki
* 선정된 프로젝트에 관한 간략한 소개
* 활동계획
* 개인별 역할에 관한 내용

활동 계획은 한주마다 업데이트 예정

**Comment by nighttwo1** [comment]
readme
-프로젝트 소개 보완 필요, 메뉴얼 추가할 부분: stage 1에 대한 정보, 게임 사진

**Comment by arensis-julia** [comment]
@nighttwo1 이거 끝났으면 close 해주세요

**Comment by arensis-julia** [comment]
@nighttwo1 실수로 닫았는데 다시 확인해주시고 close 해주세요
