### ISSUE TITLE
Beta testing result

### ISSUE THREAD

**Issue by nighttwo1** [18-2-SKKU-OSS/2018-2-OSS-E2#8]
problem(버그)
- player 창에 들어가면 게임이 종료되어버림.
- skill 창에 들어가서 item 클릭하면 겹쳐보이면서 깜박거림.

opinion
- 메뉴얼이 없어서 게임을 하는 방법을 알기 어려웠음. 조작방법이나 버튼 등의 의미를 readme에 작성하는 것이 좋을 듯.
- 세팅이 제대로 안되면 바닥에 있는 물건을 집는데 화면이 꺼지는 현상이 나타나고 컨트롤러 인식이 잘 안됨.
- stage 1까지 밖에 구현이 안됨.

**Comment by arensis-julia** [comment]
Q. player 창에 들어가면 게임이 종료된다
가장 최근 build file 이 맞는지 확인 요망

**Comment by arensis-julia** [comment]
Q. 컨트롤러 인식
A. 환경 세팅이 문제고 현재 Unity 에서 컨트롤 할 수 있는 부분은 아님

**Comment by nighttwo1** [comment]
> Q. player 창에 들어가면 게임이 종료된다
> 가장 최근 build file 이 맞는지 확인 요망

code를 clone해왔기때문에 최근 파일이라고 생각됨.

**Comment by nighttwo1** [comment]
player 창에 들어가면 게임이 종료되어버림. 이거 두번째로 베타 테스트 하러 갔을 때 수정되어있었는데 누가 했는지 알려주세요!
